services:
  authorization-db:
    image: postgres
    container_name: authorization-db
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_USER: authorization
      POSTGRES_DB: authorization
      POSTGRES_PASSWORD: authorization
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - authorization_data:/var/lib/postgresql/data
    networks:
      - authorization-db-network

  authorization-api:
    build: .
    restart: always
    container_name: authorization-api
    environment:
      PORT_APP: 9090
      DB_SGDB: postgresql
      DB_HOST: authorization-db
      DB_PORT: 5432
      DB_NAME: authorization
      DB_SCHEMA: hackaton
      DB_USER: authorization
      DB_PASSWORD: authorization
      JWT_SECRET: 123456789
    ports:
      - "9090:9090"
    depends_on:
      - authorization-db
    networks:
      - authorization-db-network

networks:
  authorization-db-network:
    driver: bridge

volumes:
  authorization_data:
