server:
  port: ${PORT_APP:9090}
  servlet:
    context-path: /authorization

spring:
  application:
    title: Microsservico Authorization
    version: 1.0
  datasource:
    url: jdbc:${DB_SGDB:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authorization}?currentSchema=${DB_SCHEMA:hackaton}
    username: ${DB_USER:authorization}
    password: ${DB_PASSWORD:authorization}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
api:
  security:
    token:
      secret: ${JWT_SECRET:123456789}
